rhel57-tmpl: &rhel57-tmpl
  template: true
  arch: linux_amd64
  provider: ec2
  settings:
    ami: ami-0c5b6364
    instancetype: m3.xlarge
    securitygroups: mci
    keyname: mci
    mountinfo: [
        {devicename: "/dev/xvdb", virtualname: "ephemeral0"}, #on m3.xlarge, this is a 40GB SSD.
        {devicename: "/dev/xvdc", virtualname: "ephemeral1"}, #on m3.xlarge, this is a 40GB SSD.
    ]
  user: root
  key: mci
  setup_as_sudo: true
  expansions: 
    decompress: tar zxvf
    ps: ps aux
    kill_pid: kill -- -$(ps opgid= %v)
  setup_mci_only: |
    echo "github.com,207.97.227.239 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" | tee -a /root/.ssh/known_hosts
    echo "${github_private_key}" | tee -a /root/.ssh/id_rsa
    echo "${github_public_key}" | tee -a /root/.ssh/id_rsa.pub
    echo "s3_key: ${s3_key}" | tee -a /data/expansions_s3.yml
    echo "s3_secret: ${s3_secret}" | tee -a /data/expansions_s3.yml
    echo "${api_httpscert}" | tee -a ${api_httpscert_path}
    chmod 600 /root/.ssh/*
    chown -R root:root /data
    chown -R root:root /root/.ssh

rhel57-build:
  <<: *rhel57-tmpl
  name: rhel57-build 
  template: false
  spawn_allowed: false
  hosts: []
  maxhosts: 5
  settings:
    ami: ami-0c5b6364
    instancetype: m3.xlarge
    securitygroups: mci
    keyname: mci
    mountinfo: [
        {devicename: "/dev/xvdb", virtualname: "ephemeral0"}, #on m3.xlarge, this is a 40GB SSD.
        {devicename: "/dev/xvdc", virtualname: "ephemeral1"}, #on m3.xlarge, this is a 40GB SSD.
    ]
  setup: |
    #!/bin/bash
    set -o errexit
    set -o verbose

    echo "making raid array"
    yes | /sbin/mdadm --create /dev/md0 --level=0 -c256 --raid-devices=2 /dev/xvdb /dev/xvdc
    /sbin/blockdev --setra 32 /dev/md0
    /sbin/mkfs.xfs -f /dev/md0
    mkdir -p /data
    echo "/dev/md0 /data auto noatime 0 0" | tee -a /etc/fstab
    mount /data
    echo "done mounting /data"

    mkdir -p /data/test_data/tmp/unittest/
    ln -s /data/test_data/tmp/unittest/ /tmp/unittest

    chown -R root:root /data

rhel57-test:
  <<: *rhel57-tmpl
  name: rhel57-test
  template: false
  spawn_allowed: true
  instancetype: m3.large
  hosts: []
  maxhosts: 10
  mountinfo: [
    {devicename: "/dev/xvdb", virtualname: "ephemeral0"}, 
  ]
  setup: |
    #!/bin/bash
    set -o errexit
    set -o verbose

    umount /dev/xvdb || true
    echo "making ephemeral drive"
    /sbin/mkfs.xfs -f /dev/xvdb
    mkdir -p /data
    mount /dev/xvdb /data

    mkdir -p /data/test_data/tmp/unittest/
    ln -s /data/test_data/tmp/unittest/ /tmp/unittest

    chown -R root:root /data
