rhel55-32: &rhel55-32
  name: rhel55-32
  arch: linux_386
  provider: ec2-spot
  spawn_allowed: false
  settings:
    bid_price: 0.01
    ami: ami-5c5b6334
    instancetype: m1.medium
    securitygroups: mci
    keyname: mci
    mountinfo: [
        {devicename: "/dev/xvdb", virtualname: "ephemeral0"}, #on m1.medium, this is a 410GB HDD.
    ]
  user: root
  key: mci
  securitygroups: mci
  setup: |
    #!/bin/bash
    set -o errexit
    set -o verbose

    /sbin/mkfs.ext4 /dev/xvdb
    echo "/dev/xvdb /data auto noatime 0 0" | tee -a /etc/fstab

    mkdir /data
    mount /data
    mkdir -p /data/test_data/tmp/unittest/
    ln -s /data/test_data/tmp/unittest/ /tmp/unittest

  setup_mci_only: |
    echo "github.com,207.97.227.239 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" | tee -a /root/.ssh/known_hosts
    echo "${github_private_key}" | tee -a /root/.ssh/id_rsa
    echo "${github_public_key}" | tee -a /root/.ssh/id_rsa.pub
    echo "s3_key: ${s3_key}" | tee -a /data/expansions_s3.yml
    echo "s3_secret: ${s3_secret}" | tee -a /data/expansions_s3.yml
    echo "${api_httpscert}" | tee -a ${api_httpscert_path}
    chmod 600 /root/.ssh/*
    chown -R root:root /data
    chown -R root:root /root/.ssh
  setup_as_sudo: true
  hosts: []
  maxhosts: 15
  expansions: 
    decompress: tar zxvf
    ps: ps aux
    kill_pid: kill -- -$(ps opgid= %v)

rhel55-32-spawn:
  <<: *rhel55-32
  name: rhel55-32-spawn
  spawn_allowed: true
  provider: ec2
