ubuntu1404-tmpl: &ubuntu1404-tmpl
  template: true
  arch: linux_amd64
  user: ubuntu
  key: mci
  hosts: []
  provider: ec2
  setup_as_sudo: true
  maxhosts: 0
  expansions: 
    decompress: tar zxvf
    ps: ps aux
    kill_pid: kill -- -$(ps opgid= %v)
  setup_mci_only: |
    echo "github.com,207.97.227.239 ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==" | tee -a /home/ubuntu/.ssh/known_hosts
    echo "${github_private_key}" | tee -a /home/ubuntu/.ssh/id_rsa
    echo "${github_public_key}" | tee -a /home/ubuntu/.ssh/id_rsa.pub
    echo "s3_key: ${s3_key}" | tee -a /data/expansions_s3.yml
    echo "s3_secret: ${s3_secret}" | tee -a /data/expansions_s3.yml
    chmod 600 /home/ubuntu/.ssh/*
    chown -R ubuntu:ubuntu /data
    chown -R ubuntu:ubuntu /home/ubuntu/.ssh


ubuntu1404-test:
  <<: *ubuntu1404-tmpl
  name: ubuntu1404-test
  spawn_allowed: true
  template: false
  provider: ec2
  settings:
    ami: ami-1d8c9574
    instancetype: m3.medium
    securitygroups: mci
    keyname: mci
    mountinfo: [
      {devicename: "/dev/xvdd", virtualname: "ephemeral0"}, #on m3.large, this is a 32GB SSD.
    ]
  maxhosts: 0
  hosts:
  setup: |
    #!/bin/bash
    set -o errexit
    set -o verbose
    # Prevent apt-get from asking questions using whiptail or dialog
    # 
    export DEBIAN_FRONTEND=noninteractive
    # wait up to 30 seconds for sources list to be updated
    #
    SOURCELIST_RECENT_MAX_MINUTES=90
    SOURCELIST_RECENT_CHECK_TIMEOUT=30
    now=`date +%s` 
    while [ ! "`find /etc/apt/sources.list -mmin -$SOURCELIST_RECENT_MAX_MINUTES`" -a "`expr \"\`date +%s\`\" - $now`" -lt $SOURCELIST_RECENT_CHECK_TIMEOUT ]  
    do 
            sleep 1 
    done
    apt-get update || true
    apt-get install --force-yes --assume-yes xfsprogs mdadm postfix golang=2:1.2.1-2ubuntu1 git

    umount /mnt || true
    umount /dev/xvdd || true
    /sbin/mkfs.xfs -f /dev/xvdd
    mkdir -p /data
    mount /dev/xvdd /data

    echo "ubuntu hard nofile 64000" | tee -a /etc/security/limits.conf
    echo "ulimit -n 64000" >> /home/ubuntu/.bashrc
    echo "ulimit -n 64000" >> /home/ubuntu/.bash_profile
    chown -R ubuntu:ubuntu /data
    chown -R ubuntu:ubuntu /home/ubuntu/.ssh

